### ISSUE TITLE
How can I restrict search with one country only?

### ISSUE THREAD

**Issue by s202394** [seatgeek/android-PlacesAutocompleteTextView#93] opened 2019-10-20 16:11 UTC
I want to restrict searching India only. How I can achieve this??

**Comment by erikswed** [comment] 2019-10-20 20:02
You can simply include the country code like this, this is some code I used 


  ```
  /**
     * Performs autocompletion for the given input text and the type of response desired. This is a
     * synchronous call, you must provide your own Async if you need it
     *
     * @param input   the textual input that will be autocompleted
     * @param type    the response type from the api
     * @param filters the filters
     * @return the places autocomplete response
     * @throws IOException the io exception
     */
    public PlacesAutocompleteResponse autocomplete(final String input, final
    GoogleAutocompleteResultType type, final Filters filters) throws IOException {
        final String finalInput = input == null ? "" : input;

        final GoogleAutocompleteResultType finalType = type == null ? DEFAULT_RESULT_TYPE : type;

        Uri.Builder uriBuilder = Uri.parse(PLACES_API_BASE)
                .buildUpon()
                .appendPath(PATH_AUTOCOMPLETE)
                .appendPath(PATH_JSON)
                .appendQueryParameter(PARAMETER_TYPE, finalType.getQueryParam())
                .appendQueryParameter(PARAMETER_KEY, googleApiKey)
                .appendQueryParameter(PARAMETER_INPUT, finalInput);

        if (filters != null) {
            if (filters.hasCountry()) {
                StringBuilder result = new StringBuilder();
                for (String c : filters.getCountries()) {
                    for (CountriesComponentType cType : CountriesComponentType.values()) {
                        if (c.toLowerCase().equals(cType.toString().toLowerCase())) {
                            result.append(PARAMETER_COMPONENT_COUNTRY);
                            result.append(cType.name().toLowerCase()); // country code
                            result.append("|");
                            break;
                        }
                    }
                }

                if (result.length() == 0) {
                    throw new RuntimeException("Country cannot have a length of 0");
                }
                // Remove last "|"
                result.replace(result.length()-1, result.length(), "");
                uriBuilder.appendQueryParameter(PARAMETER_COMPONENETS, result.toString());
                // query = query.whereEqualTo(AddressMetaSearchData.COUNTRY, filters.getCountry().toLowerCase());
            }
        }
        if (locationBiasEnabled && currentLocation != null) {
            uriBuilder.appendQueryParameter(PARAMETER_LOCATION, LocationUtils.toLatLngString(currentLocation));
        }

        if (locationBiasEnabled && radiusM != null) {
            uriBuilder.appendQueryParameter(PARAMETER_RADIUS, radiusM.toString());
        }

        if (!locationBiasEnabled) {
            uriBuilder.appendQueryParameter(PARAMETER_LOCATION, LocationUtils.toLatLngString(NO_BIAS_LOCATION));
            uriBuilder.appendQueryParameter(PARAMETER_RADIUS, NO_BIAS_RADIUS.toString());
        }

        if (languageCode != null) {
            uriBuilder.appendQueryParameter(PARAMETER_LANGUAGE, languageCode);
        }

        return httpClient.executeAutocompleteRequest(uriBuilder.build());
    }
```

**Comment by Manjunathbs412** [comment] 2020-04-11 11:48
You just need to add this line : In PlacesApi class
uriBuilder.appendQueryParameter(PARAMETER_COMPONENT, "country:de");

**Comment by hulisani-mudimeli** [comment] 2020-06-09 21:14
@Manjunathbs412  The file is read-only

**Comment by hulisani-mudimeli** [comment] 2020-06-11 08:40
Is there a solution to this? If not, can someone please tell me if you know of a library with that functionality

**Comment by TaslimOseni** [comment] 2020-10-01 20:49
Hi @hulisani-mudimeli, did you eventually get a solution to this or did you use an alternative library?

**Comment by TaslimOseni** [comment] 2020-10-02 15:44
Hi all,

I created [a PR](https://github.com/seatgeek/android-PlacesAutocompleteTextView/pull/96) to resolve this issue. I hope it gets merged asap.

**Comment by zakwanibrahim** [comment] 2021-05-18 12:10
did anyone finds solution to restrict the search to one country?????

**Comment by zakwanibrahim** [comment] 2021-05-18 12:11
> You just need to add this line : In PlacesApi class
> private static final String PARAMETER_COMPONENT = "components";
> uriBuilder.appendQueryParameter(PARAMETER_COMPONENT, "country:de");

those classes are read only ... please tell us how to edit those???

**Comment by sddamico** [comment] 2021-06-01 15:46
duplicate of #35 which has been resolved

**Closed by sddamico** 2021-06-01 15:46 UTC
